### ISSUE TITLE
No attribute 'SegNet' issue.

### ISSUE THREAD

**Issue by khuang0312** [adriankucharski/WNet-UNet-SegNet-corneal#1]
Hello, I'm looking into using your implementation for a project that is looking into automated segmentation of the corneal endothelium. I ran into some issues running the code.

So far,

I have the required dependncies:
Windows 10 64-bit
Python 3.8
TensorFlow 2.3.1
SciKit-Image

I ran prepare_dataset.py. Then I assumed you run training.py before you run predict.py. However, when you run training.py, this issue occurs. I am wondering whether I'm missing a step.

```
khuang0312@LAPTOP-VKPK88CK:/mnt/d/Documents/Homework/4th year/BIO 199/WNet-UNet-SegNet-corneal$ python3 ./training.py
['SegNet', ' WNet', ' UNet']
Traceback (most recent call last):
  File "./training.py", line 25, in <module>
    models = [[name, getattr(models, name)((*patch_size, 1))] for name in models]
  File "./training.py", line 25, in <listcomp>
    models = [[name, getattr(models, name)((*patch_size, 1))] for name in models]
AttributeError: 'list' object has no attribute 'SegNet'
```

Is the order supposed to be prepare_dataset.py, training.py, and then predict.py?

**Comment by adriankucharski** [comment]
Hello,
The problem was with "import models" and "models = ..." I accidentally overwritten import models with python list in this line:
`models` = config['Training']['network'].split(',')`
I fixed it and now it should works fine. 

The order is prepare_dataset.py, training.py and finally predict.py. Scripts also should create directories, so you do not need to create them.

**Comment by khuang0312** [comment]
Solved.
